repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
        language_version: python3.10
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        # Replace the version below with the latest pyright version
        additional_dependencies: ["pyright@1.1.239"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]