on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: datapact
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v3
        if: ${{ steps.release.outputs.release_created }}
      - run: pip install build
        if: ${{ steps.release.outputs.release_created }}
      - run: python3 -m build
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish package to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
